name: Run tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hammer_cli_foreman_openscap
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7
          - 3.0
          - 3.1

    steps:
      - name: Get hammer-cli
        uses: actions/checkout@v2
        with:
          repository: theforeman/hammer-cli
          ref: master
          path: hammer-cli
      - name: Get hammer-cli-foreman
        uses: actions/checkout@v2
        with:
          repository: theforeman/hammer-cli-foreman
          ref: master
          path: hammer-cli-foreman
      - name: Get hammer_cli_foreman_openscap
        uses: actions/checkout@v2
        with:
          repository: theforeman/hammer_cli_foreman_openscap
          ref: master
          path: hammer_cli_foreman_openscap
      - name: Configure local gem dependencies
        run: |
          echo "gemspec path: '../hammer-cli', name: 'hammer_cli'" > Gemfile.local.rb
          echo "gemspec path: '../hammer-cli-foreman', name: 'hammer_cli_foreman'" >> Gemfile.local.rb
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: hammer_cli_foreman_openscap
      - name: Run tests
        run: |
          bundle exec rake test
